python/django/rss/mysite/urls.py
from django.contrib import admin
from django.urls import include, path   # includeをimport

urlpatterns = [
    path('todo/', include('todo.urls')),    # todo/でアクセスした際はtodoのurl設定を参照させる
    path('admin/', admin.site.urls),
]

python/django/rss/todo/urls.py
from django.urls import path
from . import views 
 
app_name = 'todo' 

urlpatterns = [
    path('list/', views.TodoListView.as_view(), name='list'), 
    path('detail/<int:pk>/', views.TodoDetailView.as_view(), name='detail'), 
    path('create/', views.TodoCreateView.as_view(), name='create'), 
    path('update/<int:pk>/', views.TodoUpdateView.as_view(), name='update'), 
    path('delete/<int:pk>/', views.TodoDeleteView.as_view(), name='delete'), 
]

python/django/rss/todo/models.py
from django.db import models 

"""
ToDOモデルは、ToDo(todo)、作成日時(created_at)、更新日時(updated_at)の属性を持つ
"""
 
class Todo(models.Model): 
    todo = models.CharField('ToDo', max_length=100, blank=False)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時',auto_now=True)
    
    def __str__(self):
        return self.todo

python/django/rss/todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        exclude = ('created_at','updated_at',)  #入力項目から作成日時、更新日時を除外

python/django/rss/todo/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Todo
from .forms import TodoForm

# Djangoで予め用意されているListView, DetailView, CreateView, UpdateView, DeleteViewを利用

# 一覧表示
class TodoListView(generic.ListView):
    """
    テンプレートを指定しないと、「モデル名_list.html」が使用される
    また、自動でページネーションも自動でやってくれる
    """
    model = Todo
    paginate_by = 5 # ページネーションが5ページまで

# 詳細表示
class TodoDetailView(generic.DetailView):
    """
    Todoの詳細表示
    テンプレートを指定しないと「モデル名_detail.html」が使用される
    """
    model = Todo

# 新規作成
class TodoCreateView(generic.CreateView):
    """
    Todoの新規作成
    テンプレートを指定しないと「モデル名_form.html」が使用される
    """
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo:list')

# 更新
class TodoUpdateView(generic.UpdateView):
    """
    Todoの新規作成
    テンプレートを指定しないと「モデル名_form.html」が使用される
    """
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo:list')

# 削除
class TodoDeleteView(generic.DeleteView):
    """
    Todoの削除
    テンプレートを指定しないと「モデル名_confirm_delete.html」が使用される
    【デフォルトの動作】
    getリクエスト・・・確認ページへ遷移
    postリクエスト・・・削除を実行
    【補足】
    レコードを削除せず、有効フラグを消す(論理削除)場合は
    deleteをオーバーライドしてその中に処理を書く
    """
    model = Todo
    success_url = reverse_lazy('todo:list')

python/django/rss/todo/templates/layout.html
<!--
{％ block ％} や extendsで共有テンプレート（複数のテンプレートで共有するレイアウト）を作成します。
子テンプレート(todo_list.html)などで定義したtitleやcontentというブロックを、親テンプレート(base.html)が参照して表示
-->

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <!-- Bootstrapをロード -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
        integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body class="bg-dark">
    {% block content %}
    {% endblock %}
</body>
</html>

python/django/rss/todo/templates/todo/todo_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
<h1>ToDoの削除</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>ToDo</th>
        <td>{{ object.todo }}</td>
    </tr>
    <tr>
        <th>作成日時</th>
        <td>{{ object.created_at }}</td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td>{{ object.updated_at }}</td>
    </tr>
</table>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"value="削除" />
</form>
<a href="{% url 'todo:list' %}">戻る</a>
{%endblock%}

python/django/rss/todo/templates/todo/todo_detail.html
{% extends 'layout.html' %}

{% block content %}
<h1>ToDoの詳細</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>ToDo</th>
        <td>{{ object.todo }}</td>
    </tr>
    <tr>
        <th>作成日時</th>
        <td>{{ object.created_at }}</td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td>{{ object.updated_at }}</td>
    </tr>
</table>
<a href="{% url 'todo:list' %}">戻る</a>
{%endblock%}

python/django/rss/todo/templates/todo/todo_form.html
<!--
    {％ url 名前 引数 ％} :urls.py の name="..." で指定した名前に対応するパス名を取得
    {％ if ... ％} ... {％ elif ... ％} ... {％ endif ％} :条件式を記述
-->

{% extends 'layout.html' %}

{% block content %}

{% if object %}
<h1>ToDoの編集</h1>
{% else %}
<h1>ToDoの作成</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form }} 
    <button type="submit">送信</button>
</form>
<a href="{% url 'todo:list' %}">戻る</a>
{%endblock%}

python/django/rss/todo/templates/todo/todo_list.html
{% extends 'layout.html' %}

{% block content %}
    <a class="btn btn-primary" role="button" href="{% url 'todo:create' %}">新規作成</a>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">ToDo</th>
      <th scope="col">作成日時</th>
      <th scope="col">更新日時</th>
      <th scope="col">操作</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object_list %}
    <tr>
      <td scope="row"><a href="{% url 'todo:detail' pk=item.id %}">{{ item.id }}</a></td>
      <td>{{ item.todo }}</td>
      <td>{{ item.created_at }}</td>
      <td>{{ item.updated_at }}</td>
      <td>
        <a class="btn btn-primary" role="button"  href="{% url 'todo:update' pk=item.id %}">編集</a>
        <a class="btn btn-danger" role="button"  href="{% url 'todo:delete' pk=item.id %}">削除</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%endblock%}